# Generated by Django 5.1 on 2024-08-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LivroModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('qtd_paginas', models.IntegerField()),
                ('descricao', models.TextField()),
                ('genero', models.CharField(max_length=255)),
            ],
        ),
    ]
