# Generated by Django 5.1 on 2024-08-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('sigla', models.CharField(max_length=2, unique=True)),
                ('nacao', models.CharField(max_length=100)),
                ('infoNacao', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
